# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec = hyprshade on vibrance2
exec-once = uwsm-app -- steam -silent
exec-once = ~/dotfiles/extras/RandomBG.sh
exec-once = [workspace special:scratchpad silent; pseudo on; size 1430 850; border_size 1] uwsm-app -- xdg-terminal-exec
