# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
show_hidden = true

[preview]
ueberzug_scale = 1
ueberzug_offset = [12.5, 5, 0, 0]

[[plugin.prepend_fetchers]]
id = "git"
url = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
url = "*/"
run = "git"

[[opener.extract]]
run = "ya pub augmented-extract --list %s"
desc = "Extract here"
