#!/usr/bin/env zsh

fd . --hidden --follow "$@" | fzf \
--info=inline \
--multi \
--layout=reverse \
--prompt='CWD > ' \
--bind 'ctrl-a:transform:echo "change-prompt(CWD > )+reload(fd . --hidden --follow)"' \
--bind 'ctrl-w:transform:echo "change-prompt(Home-File > )+reload(fd . ~ --hidden --follow --type f)"' \
--bind 'ctrl-e:transform:echo "change-prompt(Home-Dir > )+reload(fd . ~ --hidden --follow --type d)"' \
--bind 'alt-c:transform:echo "change-prompt(CWD-Dir > )+reload(fd --hidden --follow --type d)"' \
--bind 'ctrl-t:transform:echo "change-prompt(CWD-File > )+reload(fd --hidden --follow --type f)"' \
--bind 'ctrl-f:transform:echo "change-prompt(Root-Dir > )+reload(fd . / --hidden --follow --type d)"' \
--bind 'ctrl-r:transform:echo "change-prompt(Root-File > )+reload(fd . / --hidden --follow --type f)"' \
--bind 'focus:transform-preview-label:echo {}' \
--preview-window 'right' \
--preview '
    printf "\033_Ga=d,q=1\033\\"
    [ -d {} ] && eza -aTL 2 --group-directories-first --color=always --icons=always {} ||
    tmp="/tmp/fzf_preview"
    case $(basename {}) in
        *.pdf)
            pdftoppm -q -f 1 -l 1 -jpeg -jpegopt quality=60 -scale-to-x 1000 -scale-to-y -1 -singlefile {} $tmp && \
            kitty icat --transfer-mode=memory --stdin=no --place=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}@0x0 $tmp.jpg
            ;;
        *.doc|*.docx|*.xls|*.xlsx|*.ppt|*.pptx|*.odt|*.ods|*.odp)
            libreoffice --convert-to jpg --outdir /tmp {} >/dev/null 2>&1
            mv "/tmp/${$(basename {})%.*}.jpg" $tmp
            kitty icat --transfer-mode=memory --stdin=no --place=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}@0x0 $tmp
            ;;
        *.djvu)
            ddjvu -format=ppm -page=1 -size 1000x-1 -aspect=yes {} $tmp 2>/dev/null && \
            kitty icat --transfer-mode=memory --stdin=no --place=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}@0x0 $tmp
            ;;
        *)
          if file --mime-type {} | grep -qP "image/(?!vnd\.djvu)"; then
            kitty icat --transfer-mode=memory --stdin=no --place=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}@0x0 {}
          else
            bat -n {} --color=always 2>/dev/null 
          fi
            ;;
    esac
'

