#!/usr/bin/env zsh

fd . --hidden --follow "$@" | fzf \
--prompt='CWD > ' \
--height=100% \
--style=default \
--info=inline \
--multi \
--cycle \
--layout=reverse \
--preview-window=wrap \
--marker="▌" \
--walker-skip .git,node_modules,target \
--bind 'ctrl-space:toggle' \
--bind 'ctrl-u:preview-half-page-up,ctrl-d:preview-half-page-down' \
--bind 'ctrl-r:transform:echo "change-prompt(Root-File > )+reload(fd . / --hidden --follow --type f)"' \
--bind 'ctrl-t:transform:echo "change-prompt(CWD-File > )+reload(fd --hidden --follow --type f)"' \
--bind 'ctrl-i:transform:echo "change-prompt(Home-File > )+reload(fd . ~ --hidden --follow --type f)"' \
--bind 'alt-q:transform:echo "change-prompt(Root-Dir > )+reload(fd . / --hidden --follow --type d)"' \
--bind 'alt-c:transform:echo "change-prompt(CWD-Dir > )+reload(fd --hidden --follow --type d)"' \
--bind 'alt-o:transform:echo "change-prompt(Home-Dir > )+reload(fd . ~ --hidden --follow --type d)"' \
--bind 'ctrl-alt-r:transform:echo "change-prompt(Root > )+reload(fd . / --hidden --follow)"' \
--bind 'ctrl-alt-q:transform:echo "change-prompt(Root > )+reload(fd . / --hidden --follow)"' \
--bind 'ctrl-alt-t:transform:echo "change-prompt(CWD > )+reload(fd . --hidden --follow)"' \
--bind 'ctrl-alt-c:transform:echo "change-prompt(CWD > )+reload(fd . --hidden --follow)"' \
--bind 'ctrl-alt-i:transform:echo "change-prompt(Home > )+reload(fd . ~ --hidden --follow)"' \
--bind 'ctrl-alt-o:transform:echo "change-prompt(Home > )+reload(fd . ~ --hidden --follow)"' \
--bind 'focus:transform-preview-label:echo {}' \
--preview-window 'right' \
--preview '$HOME/dotfiles/extras/fzf-preview.sh {}'
