#!/usr/bin/env zsh

fd . --hidden --follow --type d "$@" | fzf \
--info=inline \
--multi \
--layout=reverse \
--prompt='CWD-Dir > ' \
--walker-skip .git,node_modules,target \
--bind 'ctrl-a:transform:echo "change-prompt(CWD > )+reload(fd . --hidden --follow)"' \
--bind 'ctrl-w:transform:echo "change-prompt(Home-File > )+reload(fd . ~ --hidden --follow --type f)"' \
--bind 'ctrl-e:transform:echo "change-prompt(Home-Dir > )+reload(fd . ~ --hidden --follow --type d)"' \
--bind 'alt-c:transform:echo "change-prompt(CWD-Dir > )+reload(fd --hidden --follow --type d)"' \
--bind 'ctrl-t:transform:echo "change-prompt(CWD-File > )+reload(fd --hidden --follow --type f)"' \
--bind 'ctrl-f:transform:echo "change-prompt(Root-Dir > )+reload(fd . / --hidden --follow --type d)"' \
--bind 'ctrl-r:transform:echo "change-prompt(Root-File > )+reload(fd . / --hidden --follow --type f)"' \
--bind 'focus:transform-preview-label:echo {}' \
--preview-window 'right' \
--preview '$HOME/dotfiles/fzf-preview.sh {}'
